// <auto-generated />
namespace Gnnovation.Sims.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MoveToNewPla : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MoveToNewPla));
        
        string IMigrationMetadata.Id
        {
            get { return "201808012101128_MoveToNewPla"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
