// <auto-generated />
namespace  Gnnovation.Sims.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddMigrationEnterprise : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMigrationEnterprise));
        
        string IMigrationMetadata.Id
        {
            get { return "201807300022177_Add-Migration Enterprise"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
