//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Infrastructure.Interfaces;
using Infrastructure.Repositories;

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;

    // customized

    // customized
    
    
    public partial class Contact : RepositoryBase<Contact,int>, IEntity<int> // customized
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contact()
        {
            this.CreatedBy = "admin";
            this.ModifiedBy = "admin";
        }
    
        public int Id { get; set; }
        public int EnterpriseId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime ModifiedAt { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Enterprise Enterprise { get; set; }
    }
}
