//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Infrastructure.Interfaces;
using Infrastructure.Repositories;

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;

    // customized

    // customized
    
    
    public partial class Server : RepositoryBase<Server,int>, IEntity<int> // customized
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int StatusId { get; set; }
        public int EnterpriseId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime ModifiedAt { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Enterprise Enterprise { get; set; }
    }
}
